apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: {{ .Namespace }}  
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:14.0  
        env:
        - name: ODOO_DATABASE_HOST
          value: "postgres"  
        - name: ODOO_ADMIN_PASSWORD
          value: "admin"  
        ports:
        - containerPort: 8069  
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"