apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Namespace }}  
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13 
        env:
        - name: POSTGRES_DB
          value: "odoo"  
        - name: POSTGRES_USER
          value: "odoo"  
        - name: POSTGRES_PASSWORD
          value: "odoo" 
        ports:
        - containerPort: 5432  
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}  