# apiVersion: v1
# kind: Namespace
# metadata:
#   name: netflix
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: meta
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
  # name: estrela-do-rock

# provider "kubernetes" {
#   config_path = "~/.kube/config"  
# }

# variable "environments" {
#   description = "Lista de ambientes para criação de namespaces"
#   type        = list(string)
#   default     = ["dev", "qa", "prod"]  

# resource "kubernetes_namespace" "namespace" {
#   for_each = toset(var.environments)

#   metadata {
#     name = each.value
#   }
# }

# resource "kubernetes_deployment" "odoo" {
#   for_each = toset(var.environments)

#   metadata {
#     name      = "odoo-app"
#     namespace = each.value  
#     labels = {
#       app = "odoo"
#     }
#   }

#   spec {
#     replicas = 1
#     selector {
#       match_labels = {
#         app = "odoo"
#       }
#     }

#     template {
#       metadata {
#         labels = {
#           app = "odoo"
#         }
#       }

#       spec {
#         container {
#           name  = "odoo"
#           image = "odoo:14.0" 
#           ports {
#             container_port = 8069
#           }
#         }
#       }
#     }
#   }
# }

apiVersion: v1
kind: Namespace
metadata:
  name: production
